# Generated by Django 2.2.24 on 2022-01-04 08:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0002_auto_20220104_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
