# Generated by Django 2.2.24 on 2022-01-04 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0003_neighborhood_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='description',
            field=models.TextField(max_length=300, null=True),
        ),
    ]
